"""add comercio_id

Revision ID: 1116020d81b7
Revises: 7603b657b1c1
Create Date: 2026-03-02 14:16:00.370967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1116020d81b7'
down_revision = '7603b657b1c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comercio_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'comercios', ['comercio_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comercio_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'comercios', ['comercio_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('comercio_id')

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('comercio_id')

    # ### end Alembic commands ###
