"""remove cadastro_completo em comercios

Revision ID: 1cd6746d6e7a
Revises: f56077e9b10c
Create Date: 2026-02-10 15:40:12.603134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd6746d6e7a'
down_revision = 'f56077e9b10c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comercios', schema=None) as batch_op:
        batch_op.drop_column('cadastro_completo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comercios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cadastro_completo', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
