"""relacao usuario comercio

Revision ID: 40655c23d473
Revises: d311fe57a5cd
Create Date: 2026-03-06 14:32:07.879469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40655c23d473'
down_revision = 'd311fe57a5cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comercios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('comercios_usuario_id_key'), type_='unique')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('usuarios_comercio_id_fkey'), type_='foreignkey')
        batch_op.drop_column('comercio_id')
        batch_op.drop_column('comercio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comercio', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('comercio_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('usuarios_comercio_id_fkey'), 'comercios', ['comercio_id'], ['id'])

    with op.batch_alter_table('comercios', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('comercios_usuario_id_key'), ['usuario_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
