"""add unidade no schema

Revision ID: 7603b657b1c1
Revises: 1cd6746d6e7a
Create Date: 2026-02-16 19:27:25.434715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7603b657b1c1'
down_revision = '1cd6746d6e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('unidade')

    # ### end Alembic commands ###
