"""senha opcional para login social

Revision ID: 90410692eafd
Revises: f4ef00989bf4
Create Date: 2026-01-26 12:04:43.639682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90410692eafd'
down_revision = 'f4ef00989bf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
