"""cria tabela comercios

Revision ID: f4ef00989bf4
Revises: a29a11486d37
Create Date: 2026-01-21 16:07:04.344257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ef00989bf4'
down_revision = 'a29a11486d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comercios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_comercio', sa.String(length=100), nullable=False),
    sa.Column('segmento', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('cadastro_completo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comercios')
    # ### end Alembic commands ###
