"""add usuario_id em comercios

Revision ID: f56077e9b10c
Revises: 4cd11e11a28f
Create Date: 2026-02-10 15:17:15.958668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56077e9b10c'
down_revision = '4cd11e11a28f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comercios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        batch_op.alter_column('nome_comercio',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('segmento',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=80),
               nullable=True)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('cnpj',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.create_unique_constraint(None, ['telefone'])
        batch_op.create_unique_constraint(None, ['usuario_id'])
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comercios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('cnpj',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=14),
               nullable=False)
        batch_op.alter_column('telefone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=11),
               nullable=False)
        batch_op.alter_column('segmento',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('nome_comercio',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
